# Generated by Django 4.2.4 on 2023-08-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='frist_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Bad'), (3, 'Not Good'), (4, 'Excelent')]),
        ),
    ]
