# Generated by Django 4.2.4 on 2023-08-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_rename_frist_name_musician_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='Album',
        ),
        migrations.AlterModelTable(
            name='musician',
            table='Musician',
        ),
    ]
